gpu: 'cuda:0'
log_every_n_steps: 50

lr: 2e-4
min_lr: 1e-7
weight_decay: 0.0

epochs: 10
warmup_epochs: 0.3
patience_epochs: 0.7

load_model: None
load_model: ckpt/egnn           # pre-trained EGNN

model: 

  name: "EGNN"
  hidden_channels: 256
  in_edge_nf: 0
  n_layers: 5
  residual: True
  attention: True
  normalize: True
  tanh: False
  cutoff: 5.0
  max_atom_type: 28
  max_chirality_type: 5
  max_num_neighbors: 32

dataset:

  batch_size: 256
  num_workers: 8
  valid_size: 0.1
  test_size: 0.1
  data_dir: './ANI-1'
  seed: 666