name: EGTF_env

channels:

  - pytorch
  - conda-forge
  - defaults

dependencies:

  - python=3.8.18
  - pyyaml
  - h5py=3.7.0
  - numpy=1.19.5
  #- torch=1.12.0
  - cudatoolkit=10.2
  - tensorboard=1.15.0
  - gxx_linux-64=5.4.0
  #- torch-geometric=2.4.0

  - pip:
    - torch==1.12.0
    - torch-geometric==2.4.0
    - torch-scatter -f https://data.pyg.org/whl/torch-1.12.0+cu102.html
    - torch-cluster -f https://data.pyg.org/whl/torch-1.12.0+cu102.html