dataset_dict:
  batch_size: 128
  data_dir: ../Data
  num_workers: 2
  seed: 666
  test_size: 0.3
  valid_size: 0.5
epochs: 1
gpu: cuda:0
load_model: pretrained_egnn.pth
log_every_n_steps: 50
lr: 0.0002
min_lr: 1.0e-07
model_dict:
  act_fn: SiLU
  act_fn_ecd: ReLU
  attention: true
  cutoff: 5
  d_model: 256
  dropout_r: 0.2
  hidden_channels: 256
  max_atom_type: 28
  max_num_neighbors: 32
  normalize: true
  num_edge_feats: 0
  num_egcl: 1
  num_encoder: 1
  num_ffn: 256
  num_heads: 4
  num_neuron: 256
  residual: true
  static_coord: true
patience_epochs: 0.3
warmup_epochs: 0.7
weight_decay: 0.0
