Load_model: pretrained_egnn.pth

epochs: 5
gpu: cuda:0
load_model: null
log_every_n_steps: 10
lr: 0.0002
min_lr: 1.0e-07
patience_epochs: 0.3
warmup_epochs: 0.7
weight_decay: 0.0

model_dict:

  act_fn: SiLU
  act_fn_ecd: SiLU
  attention: true
  cutoff: 5.0
  d_model: 256
  dropout_r: 0.1
  hidden_channels: 256
  max_atom_type: 28
  max_num_neighbors: 32
  normalize: true
  num_edge_feats: 0
  num_egcl: 3
  num_encoder: 2
  num_ffn: 256
  num_heads: 4
  num_neuron: 256
  residual: true

dataset_dict:

  batch_size: 128
  data_dir: ../Data
  num_workers: 2
  seed: 666
  test_size: 0.1
  valid_size: 0.1